parameters:
#    zero_user.example.class: Zero\UserBundle\Example

services:
#    zero_user.example:
#        class: %zero_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
